Update glow and portal dependencies
ansys/ansys-templates pull request #287
Opened 2023-06-30 09:25 UTC by vgelbgras

In this PR, I updated the glow and portal dependencies to the latest version.
The .env file is adjusted to the latest change in the portal.

**_To be merged after the release of glow_**

2023-07-06 05:44 UTC, iazehaf requested changes
@vgelbgras the poetry.lock needs to be updated as well. Otherwise the installation will fail. Updating the solution templates also include the `osl-solution`. Could you please make the same changes?

2023-07-06 06:34 UTC, vgelbgras commented
> @vgelbgras the `poetry.lock` needs to be updated as well. Otherwise the installation will fail. Updating the solution templates also include the `osl-solution`. Could you please make the same changes?

I updated for the portal.
glow 0.3.0 is not released yet. We need to wait for it.

2023-07-06 06:38 UTC, iazehaf commented
> > @vgelbgras the `poetry.lock` needs to be updated as well. Otherwise the installation will fail. Updating the solution templates also include the `osl-solution`. Could you please make the same changes?
> 
> I updated for the portal. glow 0.3.0 is not released yet. We need to wait for it.

Yes I know. I believe the `.env` file of the `osl-solution` template also needs to be updated. Don't you think.

2023-07-10 07:25 UTC, iazehaf approved these changes

2023-07-10 07:31 UTC, merged