implement project commands
ansys/ansys-templates pull request #326
Opened 2023-08-26 17:39 UTC by ansRMorin

2023-08-31 10:21 UTC, iazehaf requested changes
@ansRMorin the button_group.py is not added to the desired structure of the cookicutter template. It's missing in the desired project structure.

2023-08-31 13:23 UTC, ansRMorin commented on src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/commands.py
> +from ansys.solutions.oscillator_progress.ui.components.button_group import ButtonGroup
good catch, done!

2023-08-31 21:08 UTC, ansRMorin commented
I had to update version of GLOW to 0.4.dev4 to get the MethodStatus for a normal transaction method. However, when I run the solution I get this error:
![image](https://github.com/ansys/ansys-templates/assets/106841265/f6a20c4c-83fe-41fa-bfc2-4b1790ec5399)
This is because GLOW upgrade to pydantic v2 and portal has not yet. To test, you can run the solution with `saf run --project <project_name>`

2023-09-01 08:42 UTC, iazehaf requested changes
@ansRMorin `problem_setup_step` needs to be replaced by `self` [here](https://github.com/ansys/ansys-templates/blob/d875bc29401229365878cef8d0da090da1bab4f5/src/ansys/templates/python/osl_solution/%7B%7Bcookiecutter.__project_name_slug%7D%7D/src/ansys/solutions/%7B%7Bcookiecutter.__solution_name_slug%7D%7D/solution/problem_setup_step.py#L427C36-L427C36). 

Commands locking works fine but I see no alert message when the command is running. The purpose of the alert message is to indicate to the user which command is running on which node. 

I recommend we rename the method `run_selected_project_command` into `control_node_state`.

I think Portal 0.4.3 is compatible with GLOW 0.4.dev4.

2023-09-01 15:34 UTC, ansRMorin commented
> @ansRMorin `problem_setup_step` needs to be replaced by `self` [here](https://github.com/ansys/ansys-templates/blob/d875bc29401229365878cef8d0da090da1bab4f5/src/ansys/templates/python/osl_solution/%7B%7Bcookiecutter.__project_name_slug%7D%7D/src/ansys/solutions/%7B%7Bcookiecutter.__solution_name_slug%7D%7D/solution/problem_setup_step.py#L427C36-L427C36).
>_done!_
> 
> Commands locking works fine but I see no alert message when the command is running. The purpose of the alert message is to indicate to the user which command is running on which node.
>_This can maybe be done at a later time in another PR. The fix is not so simple because you can't reliably update the same property of a component with two transaction methods. I would have to use a similar approach that I used to update the state of the buttons. One transaction updates the entire button group the second transaction method updates the state of each inidividual button (seems like I'm cheating the system here)_

> I recommend we rename the method `run_selected_project_command` into `control_node_state`.
_done!_

> I think Portal 0.4.3 is compatible with GLOW 0.4.dev4.
_I updated the portal to 0.4.3, but now I'm seeing this issue when I run the solution:_
![image](https://github.com/ansys/ansys-templates/assets/106841265/3cad80df-dafb-400c-828f-351f7eb690da)

2023-09-05 08:26 UTC, iazehaf commented
> > @ansRMorin `problem_setup_step` needs to be replaced by `self` [here](https://github.com/ansys/ansys-templates/blob/d875bc29401229365878cef8d0da090da1bab4f5/src/ansys/templates/python/osl_solution/%7B%7Bcookiecutter.__project_name_slug%7D%7D/src/ansys/solutions/%7B%7Bcookiecutter.__solution_name_slug%7D%7D/solution/problem_setup_step.py#L427C36-L427C36).
> > _done!_
> > Commands locking works fine but I see no alert message when the command is running. The purpose of the alert message is to indicate to the user which command is running on which node.
> > _This can maybe be done at a later time in another PR. The fix is not so simple because you can't reliably update the same property of a component with two transaction methods. I would have to use a similar approach that I used to update the state of the buttons. One transaction updates the entire button group the second transaction method updates the state of each inidividual button (seems like I'm cheating the system here)_
> 
> > I recommend we rename the method `run_selected_project_command` into `control_node_state`.
> > _done!_
> 
> > I think Portal 0.4.3 is compatible with GLOW 0.4.dev4.
> > _I updated the portal to 0.4.3, but now I'm seeing this issue when I run the solution:_
> > ![image](https://user-images.githubusercontent.com/106841265/265063895-3cad80df-dafb-400c-828f-351f7eb690da.png)

@ansRMorin this is due to a bug on Portal 0.4.3 wheelhouse. Switching yo 0.5.dev0 resolves the issue. We are good to merge this PR. Nice work here!

2023-09-05 08:27 UTC, iazehaf approved these changes

2023-09-05 08:30 UTC, merged