Iazehaf/fix bug 665
ansys/ansys-templates pull request #366
Opened 2023-10-03 13:33 UTC by iazehaf

2023-10-03 15:03 UTC, asbfall requested changes

2023-10-03 15:03 UTC, asbfall commented on src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py
> +        self=StepSpec(
why do we need to clean the method assets directory? I think we have a design issue here. oSL should not use the asset folder as a working directory

2023-10-03 15:46 UTC, iazehaf commented on src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/monitoring_step.py
> +        osl_logs = open(self.osl_log_file.path, 'w')
Changed to OSL logs

2023-10-03 20:19 UTC, ansRMorin commented
I'm running into this error when I start the analysis on the hook_optimization.owa use case: 
![1831a0d5-168f-4f2b-bee6-4eacc49646d8](https://github.com/ansys/ansys-templates/assets/106841265/1c75edd7-2d9a-43cd-8eea-c9d706870f39)

2023-10-04 14:59 UTC, ansRMorin approved these changes

2023-10-04 15:58 UTC, asbfall approved these changes

2023-10-05 06:30 UTC, merged